
#ifndef AREA_H
#define AREA_H

#include <iostream>
#include <cmath>

#define _USE_MATH_DEFINES

//#DEFINE PI 3.1415

void area_tri(float lado);
void area_retan(float base, float altura);
void area_quad(float lado);
void area_circ(float raio);
void area_pira(float aresta, float altura);
void area_cubo(float aresta);
void area_para(float a1, float a2, float a3);
void area_esfera(float raio);

#endif

